language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm


before_script:
  ## Packages
  - sudo apt-get -qq update > /dev/null
  ## Composer
  - composer self-update
  - composer install --prefer-source --dev
  - phpenv global "$TRAVIS_PHP_VERSION"
  - if [ $TRAVIS_PHP_VERSION = '5.6' ]; then PHPUNIT_FLAGS="--coverage-clover coverage.clover"; else PHPUNIT_FLAGS=""; fi

script:
  ## PHP_CodeSniffer
  ##- ./vendor/bin/phpcs --report-width=200 --report-summary  --report-full Classes/ unitTests/ --standard=PSR2 -n
  ## PHPUnit
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpunit $PHPUNIT_FLAGS;
notifications:
  email: false